default_platform(:ios)

platform :ios do
  desc "Build Flutter iOS release IPA without codesign"
  lane :build_release_ipa do
    sh("cd .. && flutter clean")
    sh("cd .. && flutter pub get")
    sh("cd .. && cd ios && pod install --repo-update")
    sh("cd .. && flutter build ipa --release --no-codesign")
  end
end