default_platform(:android)

platform :android do
  desc "Build Flutter Android release APK"
  lane :build_release_apk do
    project_root = File.expand_path("../..", __dir__)

    sh("cd '#{project_root}' && flutter clean")
    sh("cd '#{project_root}' && flutter pub get")
    sh("cd '#{project_root}' && flutter build apk --release --target lib/app/main.dart")
  end
end